version: "3.8"
services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: yugiohadmin
      POSTGRES_PASSWORD: yugiohpass
      POSTGRES_DB: yugiohdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://yugiohadmin:yugiohpass@db:5432/yugiohdb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
